name: pytest
on:
  pull_request:
    branches: 
    - '**'
  
jobs: 
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout root repository
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository_owner }}/P7-Project"
          ref: "main"
          path: "${{ github.workspace }}/"
          token: "${{ secrets.PAT }}"

      - name: Checkout frontend repository
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository_owner }}/P7-Frontend"
          path: "${{ github.workspace }}/frontend"
          token: "${{ secrets.PAT }}"

      - name: Checkout backend repository
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository_owner }}/P7-Backend"
          ref: "main"
          path: "${{ github.workspace }}/backend"
          token: "${{ secrets.PAT }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images with Docker compose
        run: |
          docker compose -f compose.dev.yml up -d --force-recreate --build

      - name: Run tests inside Docker
        working-directory: "${{ github.workspace }}/backend"
        run: |
          docker compose -f compose.dev.yml exec -T backend pytest
          