name: Pytest
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: 
    - '**'
  
jobs: 
  run-pytest:
    name: Run Pytest
    runs-on: ubuntu-latest
    # Skip for draft PRs
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
    steps:
      - name: Checkout root repository
        uses: actions/checkout@v6
        with:
          repository: "${{ github.repository_owner }}/P7-Project"
          ref: "main"
          path: "${{ github.workspace }}/"
          token: "${{ secrets.PAT }}"

      - name: Checkout frontend repository
        uses: actions/checkout@v6
        with:
          repository: "${{ github.repository_owner }}/P7-Frontend"
          ref: "main"
          path: "${{ github.workspace }}/frontend"
          token: "${{ secrets.PAT }}"

      - name: Checkout backend repository
        uses: actions/checkout@v6
        with:
          repository: "${{ github.repository_owner }}/P7-Backend"
          path: "${{ github.workspace }}/backend"
          token: "${{ secrets.PAT }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images with Docker compose
        run: |
          docker compose -f compose.dev.yml up -d --force-recreate --build

      - name: Run Pytest inside Docker
        run: |
          sleep 10
          docker compose -f compose.dev.yml run --rm backend pytest --ignore=test/locust_test
